### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by too-soon** [pmbaldha/WP-Custom-List-Table-With-Database-Example#1]
If anyone is interested, line [349](https://github.com/pmbaldha/WP-Custom-List-Table-With-Database-Example/blob/master/custom-list-table-db-example.php#L349) should read:

`$paged = isset($_REQUEST['paged']) ? max(0, intval($_REQUEST['paged'] - 1) * $per_page) : 0;`

For correct pagination.

**Comment by eiver** [comment]
Exactly. Noticed that too. Created pull request.

**Comment by Roy-Orbison** [comment]
I prefer at the `prepare()` so that the variable stays the same as the query value:  
`, $per_page, $paged` -> `, $per_page, $per_page * $paged`
